name: binary_serializable
description: Efficient binary serialization and deserialization, optimized for streams of binary data.
version: 0.4.1

repository: https://github.com/dart-community/binary_serializable/tree/main/packages/binary_serializable

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  meta: ^1.19.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  collection: ^1.19.1
  lints: ^6.1.0
  pretty_bytes: ^6.3.0
  test: ^1.33.0
