name: example
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  binary_serializable: ^0.4.1

dev_dependencies:
  binary_serializable_generator: ^0.5.1
  build_runner: ^2.16.2
