name: binary_serializable_workspace
publish_to: none

environment:
  sdk: ^3.5.0-243.0.dev

workspace:
  - packages/binary_serializable
  - packages/binary_serializable_generator
  # - packages/example
