name: Publish to pub.dev

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags: ["[A-z]+-v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    permissions:
      id-token: write
      pull-requests: write

    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
